version: '3.8'

services:
  node01:
    build: .
    container_name: node01
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"

